server:
  port: 9090

logging:
  level:
    org:
      springframework:
        orm:
          jpa: info
        transaction: trace
        web:
          client:
            RestTemplate: debug
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql:
              BasicBinder: trace

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: none

  sql:
    init:
      mode: always
---
spring:
  config:
    activate:
      on-profile: default
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6542/wallet-db
    username: user
    password: password
---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:wallet
    username: test
    password: test
