create table if not exists users
(
    id    bigint generated by default as identity primary key,
    first_name  varchar(32) not null,
    second_name  varchar(32) not null,
    email varchar(50) not null,
    constraint uq_user_email unique (email)
);

create table if not exists wallets
(
    id    bigint generated by default as identity primary key,
    user_id bigint not null
        constraint wallets_users_id_fk
            references users,
    created timestamp without time zone not null,
    balance decimal (8, 2)
);

create table if not exists transactions
(
    id    bigint generated by default as identity primary key,
    sender_wallet_id bigint
        constraint transactions_from_sender_wallets_id_fk
            references wallets,
    receiver_wallet_id bigint not null
        constraint transactions_to_receiver_wallets_id_fk
            references wallets,
    created timestamp without time zone not null,
    amount decimal (8, 2)
);